# Generated by Django 5.2.16 on 2026-08-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
