# Generated by Django 5.2.16 on 2026-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_usermodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
