# Generated by Django 5.2.16 on 2026-09-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profilemodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='name',
            new_name='first_name',
        ),
    ]
