# Generated by Django 5.2.16 on 2026-08-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usertokenmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokenmodel',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
