# Generated by Django 5.2.16 on 2026-09-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticAttributeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='variantattributevaluemodel',
            name='unique_non_selective_attribute',
        ),
        migrations.RemoveField(
            model_name='variantattributevaluemodel',
            name='selective',
        ),
        migrations.AddField(
            model_name='staticattributemodel',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_attributes', to='product.attributemodel'),
        ),
        migrations.AddField(
            model_name='staticattributemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_attributes', to='product.productmodel'),
        ),
        migrations.AddConstraint(
            model_name='staticattributemodel',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='unique_static_attribute_value'),
        ),
    ]
