# Generated by Django 5.2.16 on 2026-09-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributemodel',
            name='key',
            field=models.CharField(choices=[('size', 'سایز'), ('color', 'رنگ'), ('material', 'جنس'), ('alert', 'اخطار')], max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='productattributemodel',
            constraint=models.UniqueConstraint(fields=('product', 'key'), name='unique_product_attribute'),
        ),
    ]
