# Generated by Django 5.2.16 on 2026-09-14 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_staticattributemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantattributevaluemodel',
            name='attribute',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='product.attributemodel'),
        ),
    ]
