# Generated by Django 5.2.16 on 2026-09-15 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_variantattributevaluemodel_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantattributevaluemodel',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='product.attributemodel'),
        ),
    ]
