# Generated by Django 5.2.16 on 2026-09-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_categorymodel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevaluemodel',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.productattributemodel'),
        ),
        migrations.AlterField(
            model_name='productattributemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.productmodel'),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productmodel'),
        ),
    ]
