# Generated by Django 5.2.16 on 2026-09-08 03:15

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_attributevaluemodel_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributemodel',
            name='is_selective',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='image',
            field=models.ImageField(upload_to=product.models.product_image_path),
        ),
    ]
