# Generated by Django 5.2.16 on 2026-09-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_variantattributevaluemodel_attribute'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variantattributevaluemodel',
            name='unique_attribute_value',
        ),
        migrations.AddConstraint(
            model_name='variantattributevaluemodel',
            constraint=models.UniqueConstraint(fields=('attribute', 'variant'), name='unique_attribute_value'),
        ),
    ]
