# Generated by Django 5.2.16 on 2026-09-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productattributemodel_is_selective_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='discount_price',
            new_name='discount_percent',
        ),
    ]
