# Generated by Django 5.2.16 on 2026-09-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_variantattributevaluemodel_unique_attribute_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='local_name',
        ),
    ]
