# Generated by Django 5.2.16 on 2026-09-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_discount_price_productmodel_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributemodel',
            name='is_selective',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='productattributemodel',
            name='key',
            field=models.CharField(choices=[('size', 'سایز'), ('color', 'رنگ'), ('material', 'جنس')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productattributemodel',
            name='type',
            field=models.CharField(choices=[('color', 'رنگ'), ('text', 'متن')], max_length=100),
        ),
    ]
