# Generated by Django 5.2.16 on 2026-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_categorymodel_local_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staticattributemodel',
            name='unique_static_attribute_value',
        ),
        migrations.AddConstraint(
            model_name='staticattributemodel',
            constraint=models.UniqueConstraint(fields=('attribute', 'product'), name='unique_product_static_attribute'),
        ),
    ]
