# Generated by Django 5.2.16 on 2026-09-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productattributemodel_is_selective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevaluemodel',
            name='price_modifier_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='base_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
